config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: %i[index show update] do
    resources :comments, only: %i[create]
  end
  
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true, length: {in: 1..500}
  
  belongs_to :project
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates :name, presence: true
  validates :status, presence: true, inclusion: { in: %w[active archived] }
  
  has_many :comments, -> { order(created_at: :desc) }

  def flip_status
    update(status: status == 'active' ? 'archived' : 'active')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    project = Project.find(params[:project_id])
    
    Comment.create(comment_params.merge(project:)) if project.status == 'active'


    redirect_to project_url(project)
  end
  
  private

  def comment_params
    params.fetch(:comment, {}).permit(:text, :project_id)
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  def index
    @projects = Project.all.order(name: :asc)
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    @project.flip_status
    
    redirect_to project_path(@project)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def project_name(project)
    case project.status
    when 'archived'
      "#{project.name} (archived)"
    else
      project.name
    end
  end
end

app/views/comments/_form.html.erb
<h2>New Comment</h2>

<%= form_with(model: comment, url: project_comments_path(comment.project)) do |form| %>
  <div>
    <%= form.text_area :text, size: "70x5" %>
    <%= form.submit "Comment", disabled: (comment.project.status == 'archived'), class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <%= render partial: "comments/show", locals: { comment: comment } %>
<% end %>

app/views/comments/_show.html.erb
<div class="rounded overflow-hidden shadow-lg">
  <div class="px-6 py-4">
    <div class="font-bold text-xl mb-2"><%= comment.created_at.to_formatted_s(:short) %></div>
    <p class="text-gray-700 text-base">
      <%= simple_format(comment.text) %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homey</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container w-full md:max-w-3xl mx-auto pt-20">
      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, url: project_path(project)) do |form| %>    
  <div class="flex items-center justify-between">
    <%= form.submit project.status == 'archived' ? 'Activate' : 'Archive', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/projects/index.html.erb
<div class="w-full">
  <h1 class="mb-4 text-3xl sm:text-4xl tracking-tight text-black-900 font-extrabold dark:text-black-200">
    Projects
  </h1>
  
  <ul>
    <% @projects.each do |project| %>
      <li><%= link_to project_name(project), project , class: 'underline' %></li>
    <% end %>
  </ul>

</div>

app/views/projects/show.html.erb
<h1 class="mb-4 text-3xl sm:text-4xl tracking-tight text-black-900 font-extrabold dark:text-black-200">
  <%= project_name(@project) %>
</h1>

<div class="flex">
  <%= render partial: "form", locals: { project: @project } %>
</div>

<%= render partial: "comments/form", locals: { comment: Comment.new(project: @project) } %>
<%= render partial: "comments/index", locals: { comments: @project.comments } %>